config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'home#index'
  resources :users
  resources :images do
    get :home, on: :collection
  end

  get 'images', to: 'home'

end

app/models/home.rb
class Home < ActiveRecord::Base
  belongs_to :image
  has_many :image
  self.per_page = 1

end

app/models/image.rb
class Image < ActiveRecord::Base
  mount_uploader :url, ImagesUploader
  belongs_to :users
  self.per_page = 6
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :images
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController


  def index
    @images = Image.all
    @images = Image.paginate(:page => params[:page])

    render "images/home"
    # @images = Image.order(created_at: :desc).paginate(:page => params[:page], :per_page => Image.count)
    #@images = @images.paginate(:page => 1, :per_page => 6)


    ## perform a paginated query:
    # @images = Image.paginate(:page => params[:page])

    # or, use an explicit "per page" limit:
    #Image.paginate(:page => params[:page], :per_page => 3)

  end
  def truncate(string, length = 20)
    string.size > length+5 ? [string[0,length],string[-5,5]].join("...") : string
  end



end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy ]
  before_action :authenticate_user!

  # GET /images
  # GET /images.json
  def index
    @images = Image.all
    @images = Image.order('created_at DESC')
    @user = current_user.id
  end

  def home
    @images = Image.all
      # @images = Image.order(created_at: :desc).paginate(:page => params[:page], :per_page => Image.count)
   #@images = @images.paginate(:page => 1, :per_page => 6)

    @images = Image.paginate(:page => params[:page])

    ## perform a paginated query:
   # @images = Image.paginate(:page => params[:page])

    # or, use an explicit "per page" limit:
    #Image.paginate(:page => params[:page], :per_page => 3)


  end
  # GET /images/1
  # GET /images/1.json
  def show

  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)
    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:url, :description, :titre, :id)

    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    # render view: 'users/show', locals: {user: my_user} #autre option, sans le @ à user
  end
  def create

    puts params[:user]
    user_params = params
    user_params = user_params.require(:user).permit!
    user = User.new user_params
    valid = user.save
    redirect_to  [user]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.haml
%h1
  Bienvenue sur le blog de Juliette Rivière !
%div.row.liste_posts
  -Image.all.each do |image|


    / Template de card
    .col-xs-4
      .card
        .card_titre
          / <div class="card_action">
          .card_author
            .media
              %a.pull-left{:href => "#"}
                %img.media-object.dp.img-circle{:alt => "Image Utilisateur", :src => "http://lorempixel.com/400/400/nature"}
            .card_author_content
              %span.card_title
                %a{:href => images_path(image.id), :title => image.titre}
                = image.titre
              %span.card_sub_title Par Juliette Rivière
        / </div>
        .card_image
          %a{:href => image_path(image.id), :title => "Conférence Web2Day"}
            %img.img-responsive{:alt => image.titre, :src => image.url }
        .card_content
          %a{:href => images_path(image.id), :title => "Conférence Web2Day"}
            %p.sous_titre
              = image.titre
              |
              = image.created_at.to_formatted_s(:long_ordinal)
            %p
              = truncate( image.description, length:200)

app/views/images/_form.html.haml
= form_for @image, :html => {:multipart => true} do |f|
  .container
    .row
      .col-xs-12.col-sm-8.col-md-6.col-sm-offset-2.col-md-offset-3
        %form{:role => "form"}
          %h2
            Formulaire d'ajout de post
            %small
          %hr.colorgraph
            .row
              .col-xs-6.col-sm-6.col-md-6
                .form-group
                  %input#titre.form-control.input-lg{:name => "image[titre]", :placeholder => "Titre", :tabindex => "1", :type => "text"}
              .col-xs-6.col-sm-6.col-md-6
                .form-group
                  %input#url.input-lg{:name => "image[url]", :placeholder => "Last Name", :style => "padding: 0px;", :tabindex => "2", :type => "file"}
            .form-group
              %textarea#description.form-control.input-lg{:name => "image[description]", :placeholder => "Entrez le texte",  :tabindex => "3", :type => "text"}

            %hr.colorgraph
              .row
                .col-xs-12.col-md-12
                  %input.btn.btn-primary.btn-block.btn-lg{:name => "commit", :type => "submit", :value => "Ajouter le post"}/

app/views/images/edit.html.haml
%h1 Editing image

= render 'form'

= link_to 'Show', @image
\|
= link_to 'Back', images_path

app/views/images/home.haml
%h1
  Bienvenue sur le blog de Juliette Rivière !
%div.row.liste_posts

  -@images.all.each do |image|


    / Template de card
    .col-xs-4
      .card
        .card_titre
          / <div class="card_action">
          .card_author
            .media
              %a.pull-left{:href => "#"}
                %img.media-object.dp.img-circle{:alt => "Image Utilisateur", :src => "http://lorempixel.com/400/400/nature"}
            .card_author_content
              %span.card_title
                %a{:href => image_path(image.id), :title => image.titre}
                = image.titre
              %span.card_sub_title Par Juliette Rivière
        / </div>
        .card_image
          %a{:href => image_path(image.id), :title => "Conférence Web2Day"}
            %img.img-responsive{:alt => image.titre, :src => image.url }
        .card_content
          %a{:href => images_path(image.id), :title => "Conférence Web2Day"}
            %p.sous_titre
              = image.titre
              |
              = image.created_at.to_formatted_s(:long_ordinal)
            %p
              = truncate( image.description, length:200)
%div.row.liste_posts
  = will_paginate @images

app/views/images/index.html.haml
%div.images_listing
  %h1 Listing images

  %table.table.table-striped.table-hover
    %thead
      %tr
        %th
          Titre
        %th
          Description
        %th
          Image
        %th
          Action

    %tbody
      - @images.each do |image|
        %tr
          %td{:style => "width:25%;"}
            = image.titre
          %td{:style => "width:25%;"}
            = truncate( image.description, length:200)
          %td{:style => "width:25%;"}
            %img.img-responsive{:alt => image.titre, :src => image.url,:style => "width:150px; height:auto;" }
          %td{:style => "width:25%;"}
            %div.btn.btn-primary
              = link_to 'Show', image_path(image)
            - if image.user == @user
              %div.btn.btn-warning
                = link_to 'Edit', edit_image_path(image)
              %div.btn.btn-danger
                = link_to 'Destroy', image, :method => :delete, :data => { :confirm => 'Are you sure?' }

  %br

  = link_to 'New Image', new_image_path

app/views/images/new.html.haml
%h1 New image

= render 'form'

= link_to 'Back', images_path

app/views/images/show.html.haml
%container
  %div.col-xs-push-2.col-xs-8.liste_posts
    %row
      %h2
        = @image.titre
    %row.center
      =image_tag @image.url, :class => "img-responsive"
      %div.col-xs-12.text-left
        Date de publication :
        = @image.created_at.to_formatted_s(:long_ordinal)

    %div.col-xs-12.text-left
      = @image.description

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogJriviere</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav id="secondNav" class="navbar navbar-default">
  <div class="container-fluid">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <div class="navbar-brand"><%= link_to "Blog de Juliette Rivière", root_path %></div>
         <a class="navbar-brand-scroll" style="display:none" href="#">Blog de Juliette Rivière</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right ">
          <li class="active "><%= link_to "Accueil", root_path %>

          </li>
          <li><%= link_to "Tous les posts", images_path %></li>
          <li><%= link_to "Ajouter une image", new_image_path %></li>
          <% if user_signed_in? %>
           <li><%= link_to "Se déconnecter",  destroy_user_session_path, :method => :delete %>
          <% else %>
              <li><%= link_to "Se connecter", user_session_path %>
              <li><%= link_to "S'inscrire", new_user_registration_path %>
          <% end %>


              </li>
        </ul>
      </div>
    </div>
  </div>
</nav>
<div class="container">

<%= yield %>
</div>
<!-- Footer -->
<footer>
  <div class="footer-bottom">
    <div class="container">
      <div class="row">
        <div class="col-md-12 copyright">
          <p class="copyright">
            Copyright &copy; 2016 <span class="company">Blog de Juliette Rivière</span>
          </p>
        </div>
      </div>
    </div>
  </div>
</footer>
</body>
</html>

app/views/users/index.html.haml
Page des utilisateurs
%ul
  -User.all.each do |user|
    %li
      Mail :
      = link_to user.email, [user]

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>